// week (days) names array
export const dayNamesStartingWithSunday = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']

// week (days) names array
export const dayNamesStartingWithMonday = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']

// variables
export const defaultVariables = {
  defaultWeekSeparatorWidth: 10,
  defaultminCellWidth: 40,
  defaultHeaderWeekendBgColor: '#b39cd0',
  defaultHeaderWeekDayBgColor: '#c3b5d5',
  defaultHeaderTextColor: 'white',
  defaultWeekSeparatorColor: '#fefedf',
  defaultWeekendCellBackgroundColor: '#b39cd0',
  defaultWeekendCellTextColor: 'white',
  defaultWeekDayCellBackgroundColor: 'white',
  defaultWeekDayCellTextColor: 'black',
  defaultSelectionColor: '#32214c',
  defaultSelectionTextColor: 'white',
  defaultMonthNameBackgroundColor: '#f2fedc',
  defaultMonthNameTextColor: 'black',
}

export const locales = {
  af: () => import('dayjs/locale/af'),
  cs: () => import('dayjs/locale/cs'),
  es: () => import('dayjs/locale/es'),
  ht: () => import('dayjs/locale/ht'),
  me: () => import('dayjs/locale/me'),
  ro: () => import('dayjs/locale/ro'),
  tlh: () => import('dayjs/locale/tlh'),
  am: () => import('dayjs/locale/am'),
  cv: () => import('dayjs/locale/cv'),
  'es-mx': () => import('dayjs/locale/es-mx'),
  hu: () => import('dayjs/locale/hu'),
  mi: () => import('dayjs/locale/mi'),
  ru: () => import('dayjs/locale/ru'),
  'tl-ph': () => import('dayjs/locale/tl-ph'),
  'ar-dz': () => import('dayjs/locale/ar-dz'),
  cy: () => import('dayjs/locale/cy'),
  'es-pr': () => import('dayjs/locale/es-pr'),
  'hy-am': () => import('dayjs/locale/hy-am'),
  mk: () => import('dayjs/locale/mk'),
  rw: () => import('dayjs/locale/rw'),
  tr: () => import('dayjs/locale/tr'),
  'ar-iq': () => import('dayjs/locale/ar-iq'),
  da: () => import('dayjs/locale/da'),
  'es-us': () => import('dayjs/locale/es-us'),
  id: () => import('dayjs/locale/id'),
  ml: () => import('dayjs/locale/ml'),
  sd: () => import('dayjs/locale/sd'),
  ar: () => import('dayjs/locale/ar'),
  'de-at': () => import('dayjs/locale/de-at'),
  et: () => import('dayjs/locale/et'),
  mn: () => import('dayjs/locale/mn'),
  se: () => import('dayjs/locale/se'),
  tzl: () => import('dayjs/locale/tzl'),
  'ar-kw': () => import('dayjs/locale/ar-kw'),
  'de-ch': () => import('dayjs/locale/de-ch'),
  eu: () => import('dayjs/locale/eu'),
  is: () => import('dayjs/locale/is'),
  mr: () => import('dayjs/locale/mr'),
  si: () => import('dayjs/locale/si'),
  tzm: () => import('dayjs/locale/tzm'),
  'ar-ly': () => import('dayjs/locale/ar-ly'),
  de: () => import('dayjs/locale/de'),
  fa: () => import('dayjs/locale/fa'),
  'it-ch': () => import('dayjs/locale/it-ch'),
  ms: () => import('dayjs/locale/ms'),
  sk: () => import('dayjs/locale/sk'),
  'tzm-latn': () => import('dayjs/locale/tzm-latn'),
  'ar-ma': () => import('dayjs/locale/ar-ma'),
  dv: () => import('dayjs/locale/dv'),
  fi: () => import('dayjs/locale/fi'),
  it: () => import('dayjs/locale/it'),
  'ms-my': () => import('dayjs/locale/ms-my'),
  sl: () => import('dayjs/locale/sl'),
  'ug-cn': () => import('dayjs/locale/ug-cn'),
  'ar-sa': () => import('dayjs/locale/ar-sa'),
  el: () => import('dayjs/locale/el'),
  fo: () => import('dayjs/locale/fo'),
  ja: () => import('dayjs/locale/ja'),
  mt: () => import('dayjs/locale/mt'),
  sq: () => import('dayjs/locale/sq'),
  uk: () => import('dayjs/locale/uk'),
  'ar-tn': () => import('dayjs/locale/ar-tn'),
  'en-au': () => import('dayjs/locale/en-au'),
  'fr-ca': () => import('dayjs/locale/fr-ca'),
  jv: () => import('dayjs/locale/jv'),
  my: () => import('dayjs/locale/my'),
  'sr-cyrl': () => import('dayjs/locale/sr-cyrl'),
  ur: () => import('dayjs/locale/ur'),
  az: () => import('dayjs/locale/az'),
  'en-ca': () => import('dayjs/locale/en-ca'),
  'fr-ch': () => import('dayjs/locale/fr-ch'),
  ka: () => import('dayjs/locale/ka'),
  nb: () => import('dayjs/locale/nb'),
  sr: () => import('dayjs/locale/sr'),
  uz: () => import('dayjs/locale/uz'),
  be: () => import('dayjs/locale/be'),
  'en-gb': () => import('dayjs/locale/en-gb'),
  fr: () => import('dayjs/locale/fr'),
  kk: () => import('dayjs/locale/kk'),
  ne: () => import('dayjs/locale/ne'),
  ss: () => import('dayjs/locale/ss'),
  'uz-latn': () => import('dayjs/locale/uz-latn'),
  bg: () => import('dayjs/locale/bg'),
  'en-ie': () => import('dayjs/locale/en-ie'),
  fy: () => import('dayjs/locale/fy'),
  km: () => import('dayjs/locale/km'),
  'nl-be': () => import('dayjs/locale/nl-be'),
  'sv-fi': () => import('dayjs/locale/sv-fi'),
  vi: () => import('dayjs/locale/vi'),
  bi: () => import('dayjs/locale/bi'),
  'en-il': () => import('dayjs/locale/en-il'),
  ga: () => import('dayjs/locale/ga'),
  kn: () => import('dayjs/locale/kn'),
  nl: () => import('dayjs/locale/nl'),
  sv: () => import('dayjs/locale/sv'),
  'x-pseudo': () => import('dayjs/locale/x-pseudo'),
  bm: () => import('dayjs/locale/bm'),
  'en-in': () => import('dayjs/locale/en-in'),
  gd: () => import('dayjs/locale/gd'),
  ko: () => import('dayjs/locale/ko'),
  nn: () => import('dayjs/locale/nn'),
  sw: () => import('dayjs/locale/sw'),
  yo: () => import('dayjs/locale/yo'),
  'bn-bd': () => import('dayjs/locale/bn-bd'),
  en: () => import('dayjs/locale/en'),
  gl: () => import('dayjs/locale/gl'),
  ku: () => import('dayjs/locale/ku'),
  'oc-lnc': () => import('dayjs/locale/oc-lnc'),
  ta: () => import('dayjs/locale/ta'),
  'zh-cn': () => import('dayjs/locale/zh-cn'),
  bn: () => import('dayjs/locale/bn'),
  'en-nz': () => import('dayjs/locale/en-nz'),
  'gom-latn': () => import('dayjs/locale/gom-latn'),
  ky: () => import('dayjs/locale/ky'),
  'pa-in': () => import('dayjs/locale/pa-in'),
  te: () => import('dayjs/locale/te'),
  'zh-hk': () => import('dayjs/locale/zh-hk'),
  bo: () => import('dayjs/locale/bo'),
  'en-sg': () => import('dayjs/locale/en-sg'),
  gu: () => import('dayjs/locale/gu'),
  lb: () => import('dayjs/locale/lb'),
  pl: () => import('dayjs/locale/pl'),
  tet: () => import('dayjs/locale/tet'),
  zh: () => import('dayjs/locale/zh'),
  br: () => import('dayjs/locale/br'),
  'en-tt': () => import('dayjs/locale/en-tt'),
  he: () => import('dayjs/locale/he'),
  lo: () => import('dayjs/locale/lo'),
  'pt-br': () => import('dayjs/locale/pt-br'),
  tg: () => import('dayjs/locale/tg'),
  'zh-tw': () => import('dayjs/locale/zh-tw'),
  bs: () => import('dayjs/locale/bs'),
  eo: () => import('dayjs/locale/eo'),
  hi: () => import('dayjs/locale/hi'),
  lt: () => import('dayjs/locale/lt'),
  pt: () => import('dayjs/locale/pt'),
  th: () => import('dayjs/locale/th'),
  ca: () => import('dayjs/locale/ca'),
  'es-do': () => import('dayjs/locale/es-do'),
  hr: () => import('dayjs/locale/hr'),
  lv: () => import('dayjs/locale/lv'),
  rn: () => import('dayjs/locale/rn'),
  tk: () => import('dayjs/locale/tk'),
}
